services:
  api:
    build:
      context: .
      dockerfile: NewsPaperAuthExample/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecret7!
      POSTGRES_DB: NewsPaper
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
